### PR TITLE
 fixes #207: Bump kafka Version

### LINKED ISSUE #207: Bump kafka Version
Bump Kafka Version to 2.3.0

### PR DESCRIPTION
**Pull request by conker84**
Fixes #207 

I asked a feedback to a Customer that has Kafka 0.10.1 so please wait to merge it.

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Update kafka to 2.3.0
  - small clean-up

### CODE REVIEW

**Comment by mneedham** [comment]
Should we merge it now?

**Comment by conker84** [comment]
I just pinged today the customer, I'm still waiting for the feedback

**Comment by moxious** [comment]
Been another month, checking in.  Presumably that feedback isn't coming?

**Comment by conker84** [comment]
Hi @moxious ,
in the specific case the new api that we're leveraging with this PR is about this KIP:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-266%3A+Fix+consumer+indefinite+blocking+behavior

**Pull request merged**
