### PR TITLE
Fix YAML for NEO4J_ACCEPT_LICENSE_AGREEMENT and add auto-install of connector

### LINKED ISSUE #152: ERROR: The Compose file './docker-compose.yml' is invalid because: services.neo4j.environment.NEO4J_ACCEPT_LICENSE_AGREEMENT contains true, which is an invalid type, it should be a string, number, or a null
## Expected Behavior (Mandatory)

From https://www.confluent.io/blog/kafka-connect-neo4j-sink-plugin I click through to https://github.com/neo4j-contrib/neo4j-streams/blob/master/kafka-connect-neo4j/docker/docker-compose.yml and per the article run

    docker-compose up -d

I expect it to bring the stack up.

## Actual Behavior (Mandatory)

```
$ docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.neo4j.environment.NEO4J_ACCEPT_LICENSE_AGREEMENT contains true, which is an invalid type, it should be a string, number, or a null
```

## How to Reproduce the Problem

Clone the repo
Run docker-compose up -d

### PR DESCRIPTION
**Pull request by rmoff**
Fixes #152

### CODE REVIEW

**Comment by rmoff** [comment]
git snafu on my part - also committed a change that adds code to the Docker Compose to automagically install the neo4j sink plugin, so that the user doesn't have to do it manually (and then restart the Connect worker for it to pick up the plugin).

**Comment by jexp** [comment]
@rmoff thanks a lot.

Do you want the 2nd commit with the auto-install/restart added?

Would you mind signing the CLA? https://neo4j.com/developer/cla/

**Comment by jexp** [comment]
Odd, it worked on my machine, when I tested the integration. Thanks for spotting it.

**Comment by rmoff** [comment]
@jexp yep the auto-install is valid to merge as well please. 
I've done the CLA needful.

**Comment by jexp** [comment]
@rmoff the twitter connector + ksql should I pull those in too? 
Or did they accidentally make it onto this branch?

If we pull them in, we probably want to amend the docs to say something about those?
(I see a new blog post coming :)

**Comment by jexp** [comment]
Thanks for the CLA

**Comment by rmoff** [comment]
@jexp sorry about that - I've reverted those pieces. This PR should be ready to go now :)

**Comment by jexp** [comment]
Thanks a lot Robin.

**Pull request merged**
